# Generated by Django 3.2.16 on 2022-12-27 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("entity_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("title", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="ReviewCycle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("entity_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("name", models.CharField(max_length=128)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="review_cycles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="review.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reviewee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("entity_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="reviewees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review_cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="review.reviewcycle",
                    ),
                ),
            ],
        ),
    ]
