# Generated by Django 3.2.16 on 2023-01-04 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("review", "0002_auto_20221227_1718"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewee",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="assigned_reviewees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reviewee",
            name="review_cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewees",
                to="review.reviewcycle",
            ),
        ),
    ]
